export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_IN_PROGRESS = 'CHANGE_EMAIL_IN_PROGRESS';
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';
export const AUTHENTICATED_CLEARDOWN = 'AUTHENTICATED_CLEARDOWN';